### ISSUE TITLE
插件运行失败

### ISSUE THREAD

**Issue by wsmwzms123** [MockForge/mockforge#4]
"vite": "5.4.4" 和 "vite": "4.4.9"两个版本
http://localhost:50930/，均报错 Cannot GET /

**Comment by myderr** [comment]
一样，甚至还提示/mockforge/dist/vite-plugin.d.ts”不是模块。ts(2306)

**Comment by DiamondYuan** [comment]
@wsmwzms123  @myderr 

0.5.0 已修复。

**Comment by myderr** [comment]
> @wsmwzms123 @myderr
> 
> 0.5.0 已修复。

export提示没问题了，但是还是Cannot GET /
使用的这个项目：https://github.com/soybeanjs/soybean-admin
![image](https://github.com/user-attachments/assets/c03d2f9d-5881-483e-8e22-cfbbfed1e62a)
![image](https://github.com/user-attachments/assets/321153dd-0b53-4bb8-a68b-82ea9e65dd20)

**Comment by DiamondYuan** [comment]
> > @wsmwzms123 @myderr
> > 0.5.0 已修复。
> 
> export提示没问题了，但是还是Cannot GET / 使用的这个项目：https://github.com/soybeanjs/soybean-admin ![image](https://private-user-images.githubusercontent.com/26431313/367135683-c03d2f9d-5881-483e-8e22-cfbbfed1e62a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxOTg4OTYsIm5iZiI6MTcyNjE5ODU5NiwicGF0aCI6Ii8yNjQzMTMxMy8zNjcxMzU2ODMtYzAzZDJmOWQtNTg4MS00ODNlLThlMjItY2ZiYmZlZDFlNjJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDAzMzYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzOGNkNjE5NTE4OTkwMTIyM2E3YTk0YmUxZmQxOWYyN2E5ZTZiNzkwZWQ1OWIwMTliNWVmMTEzOTAzOTllZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nJFIfuRhoVJHGMXCLbOs_kWuGqimIXRC29Lh-f-VEeA) ![image](https://private-user-images.githubusercontent.com/26431313/367135929-321153dd-0b53-4bb8-a68b-82ea9e65dd20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxOTg4OTYsIm5iZiI6MTcyNjE5ODU5NiwicGF0aCI6Ii8yNjQzMTMxMy8zNjcxMzU5MjktMzIxMTUzZGQtMGI1My00YmI4LWE2OGItODJlYTllNjVkZDIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDAzMzYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1YmM5NzkwNDU0NTc2YWQ3YWY2ZWRjMjdiMDBhNWI2ZmI3YWI0YmU5Nzc5YzZlMDgxYTY1Y2M5ZjRlODViMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gc_eEBIhCSXKNCs6gVEAoaUgbCndvYOHO5asMtJRom4)



<img width="786" alt="image" src="https://github.com/user-attachments/assets/e90b2234-b900-4f51-b007-8be952f820a8">

![image](https://github.com/user-attachments/assets/05cbd06e-3b06-4c9f-83e0-f1be18681369)

请问你本地的 nodejs 版本是什么？ 我在这个项目试了一下没什么问题

**Comment by myderr** [comment]
> > > @wsmwzms123 @myderr
> > > 0.5.0 已修复。
> > 
> > 
> > export提示没问题了，但是还是Cannot GET / 使用的这个项目：https://github.com/soybeanjs/soybean-admin ![image](https://private-user-images.githubusercontent.com/26431313/367135683-c03d2f9d-5881-483e-8e22-cfbbfed1e62a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxOTg4OTYsIm5iZiI6MTcyNjE5ODU5NiwicGF0aCI6Ii8yNjQzMTMxMy8zNjcxMzU2ODMtYzAzZDJmOWQtNTg4MS00ODNlLThlMjItY2ZiYmZlZDFlNjJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDAzMzYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzOGNkNjE5NTE4OTkwMTIyM2E3YTk0YmUxZmQxOWYyN2E5ZTZiNzkwZWQ1OWIwMTliNWVmMTEzOTAzOTllZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nJFIfuRhoVJHGMXCLbOs_kWuGqimIXRC29Lh-f-VEeA) ![image](https://private-user-images.githubusercontent.com/26431313/367135929-321153dd-0b53-4bb8-a68b-82ea9e65dd20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxOTg4OTYsIm5iZiI6MTcyNjE5ODU5NiwicGF0aCI6Ii8yNjQzMTMxMy8zNjcxMzU5MjktMzIxMTUzZGQtMGI1My00YmI4LWE2OGItODJlYTllNjVkZDIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDAzMzYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1YmM5NzkwNDU0NTc2YWQ3YWY2ZWRjMjdiMDBhNWI2ZmI3YWI0YmU5Nzc5YzZlMDgxYTY1Y2M5ZjRlODViMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gc_eEBIhCSXKNCs6gVEAoaUgbCndvYOHO5asMtJRom4)
> 
> <img alt="image" width="786" src="https://private-user-images.githubusercontent.com/9692408/367140156-e90b2234-b900-4f51-b007-8be952f820a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxOTkwNjAsIm5iZiI6MTcyNjE5ODc2MCwicGF0aCI6Ii85NjkyNDA4LzM2NzE0MDE1Ni1lOTBiMjIzNC1iOTAwLTRmNTEtYjAwNy04YmU5NTJmODIwYTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTNUMDMzOTIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjgwZWU2ODY1OWEyZWRmMTRlMTdmNjBjNTAzOTY2OGFmM2EzNjA1ZDFlMDgxYTY1MDNmNGJkNTk0ODk0NWY3NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.z2SEpPz5upY9vMS8v1L_-d_8PdbV4zvhBPtAn-T_jbw">
> ![image](https://private-user-images.githubusercontent.com/9692408/367140188-05cbd06e-3b06-4c9f-83e0-f1be18681369.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxOTkwNjAsIm5iZiI6MTcyNjE5ODc2MCwicGF0aCI6Ii85NjkyNDA4LzM2NzE0MDE4OC0wNWNiZDA2ZS0zYjA2LTRjOWYtODNlMC1mMWJlMTg2ODEzNjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTNUMDMzOTIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDM2YmQ5M2NhMzM1MDg4N2U4NWQ2ZWMzZjEyYzZmYWI5YmEwNWQ0ZDkzZGVkMmJkZGY5MmYxMGYxYjJlNjhjNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dOHM7U5AFqUJqUdbS4ZXHnRe2XlkHOYvgG6tXyBEE84)
> 
> 请问你本地的 nodejs 版本是什么？ 我在这个项目试了一下没什么问题

![image](https://github.com/user-attachments/assets/c6392cff-0acb-405c-83ea-ba1c4acd55d0)

**Comment by DiamondYuan** [comment]
@myderr  不好意思，没办法复现你的问题。  今天晚点我在我的 windows 电脑上试试看。



https://github.com/mockforge/mockforge/blob/aa10e558d7996359e4317b70b1557c8162b25c10/src/server/node/server.ts#L39
我就是在本地启动了 extress ，然后托管了静态文件。 从代码里没发现问题

**Comment by DiamondYuan** [comment]
@myderr  @wsmwzms123 

在 0.6.0 修复了这个问题。 主要是 __dirname 的逻辑出错了。
